---
# vars file for ec2
instance_tag:
        - master
        - slave1
        - slave2

sg_name: Allow_All_SG
instance_id: i-0305e5385bbd48dca
region_name: us-east-2
subnet_name: subnet-d39aa79f
ami_id: ami-064ff912f78e3e561
keypair: ubuntukey
instance_flavour: t2.large
