---
# vars file for ec2
instance_tag:
        - master
        - slave1
        - slave2

python_pkgs:
        - boto
        - boto3

sg_name: Allow_All_SG
region_name: us-east-2
subnet_name: subnet-d39aa79f
ami_id: ami-064ff912f78e3e561
keypair: ubuntukey
instance_flavour: t2.large
