---
- name: Terminate Instances
  ec2:
    instance_ids: "{{ instance_id }}"
    region: us-east-2
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    state: absent
    wait: yes
